"use client";

import { ConfigProvider } from "antd";
import { Libre_Franklin, Inter } from "next/font/google";

const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["300", "600", "700"],
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "hsl(223, 87%, 63%)",
              colorBgLayout: "#FFF",
              fontFamily: libreFranklin.style.fontFamily,
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
};

export default RootLayout;
